---
- hosts: all
  become: true

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.ntp" }
    - { role: "azavea.nodejs" }
    - { role: "azavea.terraform" }
    - { role: "azavea.git" }
    - { role: "mmw-micro.environment" }
    - { role: "mmw-micro.awscli" }
    - { role: "mmw-micro.shellcheck" }
